//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap _lock {
            get {
                object obj = ResourceManager.GetObject("_lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap acrobat {
            get {
                object obj = ResourceManager.GetObject("acrobat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Process complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string done {
            get {
                return ResourceManager.GetString("done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Saving failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string error1 {
            get {
                return ResourceManager.GetString("error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File is busy. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string error2 {
            get {
                return ResourceManager.GetString("error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap excel {
            get {
                object obj = ResourceManager.GetObject("excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   This workbook has been read password-protected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string excel1 {
            get {
                return ResourceManager.GetString("excel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This workbook has been write password-protected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string excel2 {
            get {
                return ResourceManager.GetString("excel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This workbook is not applied password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string excel3 {
            get {
                return ResourceManager.GetString("excel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This workbook&apos;s permission is set to shared with multi users. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string excel4 {
            get {
                return ResourceManager.GetString("excel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string message1 {
            get {
                return ResourceManager.GetString("message1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password is incorrect. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string message2 {
            get {
                return ResourceManager.GetString("message2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   It&apos;s possible to set only read-password as zip file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string message3 {
            get {
                return ResourceManager.GetString("message3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap open3 {
            get {
                object obj = ResourceManager.GetObject("open3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   This PDF file has been password-protected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string pdf1 {
            get {
                return ResourceManager.GetString("pdf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This PDF file does not have an applied password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string pdf2 {
            get {
                return ResourceManager.GetString("pdf2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This PDF file has been user password-protected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string pdf3 {
            get {
                return ResourceManager.GetString("pdf3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This PDF file has been owner password-protected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string pdf4 {
            get {
                return ResourceManager.GetString("pdf4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap powerpoint {
            get {
                object obj = ResourceManager.GetObject("powerpoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   This presentation has been password-protected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string powerpoint1 {
            get {
                return ResourceManager.GetString("powerpoint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This presentation does not have an applied password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string powerpoint2 {
            get {
                return ResourceManager.GetString("powerpoint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap question {
            get {
                object obj = ResourceManager.GetObject("question", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap trash {
            get {
                object obj = ResourceManager.GetObject("trash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap unlock {
            get {
                object obj = ResourceManager.GetObject("unlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap word {
            get {
                object obj = ResourceManager.GetObject("word", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   This document has been read password-protected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string word1 {
            get {
                return ResourceManager.GetString("word1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This document has been write password-protected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string word2 {
            get {
                return ResourceManager.GetString("word2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This document does not have an applied password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string word3 {
            get {
                return ResourceManager.GetString("word3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap zip {
            get {
                object obj = ResourceManager.GetObject("zip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   This Zip file has been password-protected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zip1 {
            get {
                return ResourceManager.GetString("zip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This Zip file does not have an applied password. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string zip2 {
            get {
                return ResourceManager.GetString("zip2", resourceCulture);
            }
        }
    }
}
